### ISSUE TITLE
ER-diagram

### ISSUE THREAD

**Issue by Ver33d** [go-park-mail-ru/2024_1_Netrunners#19]
В ER diagram не отображена (#16 ) таблица film_actor

**Comment by ns-roxer** [comment]
1. sequence надо заменить на identity
Поясняю:
молодцы, что не использовали serial, как того требовали условия задачи.
Но нет в вашем случае использовать низкоуровневый механизм sequence и работать с ним напрямую.
Сейчас полезнее будет разобраться с indentity 
 
2. 
PRIMARY KEY + UNIQUE не имеет никакого смысла!
PRIMARY KEY = UNIQUE + NOT NULL
А вы на ровном месте сделали ДВА индекса на каждый id атрибут каждой таблицы

3. "uuid" - это тип, это слово очень плохо подходит для названия колонки, так как не несет никакой смысловой нагрузки.
Если это айдишник, который вы хотите выдавать наружу с бэкенда, а id, оставить инкапсулированным в БД и бэкенде, то назовите, например, "external_id"

**Comment by ns-roxer** [comment]
Зачтено, @Ver33d закрой, пожалуйста, issue
